version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  web:
    build:
      context: collabfield
    volumes:
      - ./collabfield:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db